FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y git

COPY tld /app/tld
COPY pyproject.toml /app/pyproject.toml
COPY tests /app/tests

RUN pip install --no-cache-dir .

CMD ["uvicorn", "tld.app:app", "--host", "0.0.0.0", "--port", "80"]
